### ISSUE TITLE
Update NPM version

### ISSUE THREAD

**Issue by roblabla** [zekesonxx/node-yggdrasil#1]
Hello, I'd be interested in using node-yggdrasil on PrismarineJS/node-minecraft-protocol , but it seems the latest version published on NPM doesn't have the `join` and `hasJoined` calls present on github. Would it be possible for you to publish it to npm, or is there work left to do, in which case can I help with anything ?

**Comment by zekesonxx** [comment]
Fixed by 890ccdd
