### ISSUE TITLE
Respect the node.js callback(err,result) convention

### ISSUE THREAD

**Issue by rom1504** [zekesonxx/node-yggdrasil#12]
Several places in the code don't call the callbacks properly.
- https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/index.js#L30 : should wrap `out` in an error object: `new Error(out)` for example
- https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/index.js#L75 : same thing
- https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/index.js#L92 : false should be second argument, with null as first if there was no error
- https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/index.js#L94 : same thing
- https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/index.js#L110 : same thing
- https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/index.js#L112 : same thing
- https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/index.js#L142 : same

I'll probably do a PR for this.

I also think it might be time to merge #11, an unit test for it can come later, having it work is more important.

**Comment by Luminess** [comment]
Did I get all of them in my pull request?
