### ISSUE TITLE
bump version to 1.0.0 ?

### ISSUE THREAD

**Issue by rom1504** [zekesonxx/node-yggdrasil#20]
I think node-yggdrasil is fairly stable.
Having a version in the 1.0.0- range would make it possible to make minor releases instead of only major releases which is better for semver. (any 0.x.x release is considered breaking)

**Comment by comp500** [comment]
I agree with this, it works very well as far as I've tested. Also, my pull request from 2 days ago still hasn't been published to npm yet.

**Comment by zekesonxx** [comment]
Yeah. I know. I'm trying to, but npm literally won't let me login. Working on figuring out why.

**Comment by zekesonxx** [comment]
There we go. Stupid thing.

v0.3.0 published since I already made the tag and everything, going to look over the code and likely do a 1.0.0 today.

**Comment by zekesonxx** [comment]
8a121badd2cd3c4eb960f58799419fe7a42e1c1e
