### ISSUE TITLE
Unexpected end of JSON Input

### ISSUE THREAD

**Issue by ArcticZeroo** [zekesonxx/node-yggdrasil#24]
Every time I attempt to log into a server using [mineflayer](https://github.com/PrisimarineJS/mineflayer), https://sessionserver.mojang.com/session/minecraft/join returns a blank response and the [JSON.parse call](https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/utils.js#L24) throws the error "SyntaxError: Unexpected end of JSON Input".

Steps to reproduce:

- Install  `mineflayer`
- Create a script which calls `mf.createBot` with a valid username/password for an online server
- Run the script, and it'll throw the error.

This seems to be an issue only as of 1.1.0.

**Comment by rom1504** [comment]
I believe the problem come from https://github.com/zekesonxx/node-yggdrasil/blob/1773c40d9128e4bf79f5d75d8a20cb24ce497eb7/lib/utils.js#L24 vs https://github.com/zekesonxx/node-yggdrasil/blob/1773c40d9128e4bf79f5d75d8a20cb24ce497eb7/lib/Server.js#L46

one of them is wrong

**Comment by rom1504** [comment]
Also the tests should cover this.

**Comment by bdsomer** [comment]
Looks like the endpoint being requested (POST https://sessionserver.mojang.com/session/minecraft/join) returns a 204 No Content (with no content). `JSON.parse` fails to parse this empty string and calls back with an error.
