### ISSUE TITLE
New NPM version

### ISSUE THREAD

**Issue by roblabla** [zekesonxx/node-yggdrasil#7]
Ohay, could you publish the last PR to NPM ? That'd let NMP (finally) use node-yggdrasil https://github.com/PrismarineJS/node-minecraft-protocol/pull/262

**Comment by roblabla** [comment]
NVM about the release, it seems like there's still a bug in the lib's `hasJoined` method. I'll hunt it down first.

**Comment by zekesonxx** [comment]
> npm version bump to 0.0.4, 0.1 will be when the server code is finished

Will look the lib over in an hour or two to see if it's suitable for getting bumped to 0.1. I think so, but I'm on my laptop and can't really accomplish anything useful on it.

**Comment by rom1504** [comment]
better merge https://github.com/zekesonxx/node-yggdrasil/pull/8 first though ;)

**Comment by zekesonxx** [comment]
closed by 59a8c42f6f177a316b0a0f29e7850cc6658e0590
